# SportSynchro CI/CD Pipeline
pool:
  vmImage: ubuntu-latest 

steps:
# Build
- task: DotNetCoreCLI@2
  displayName: Build Projects
  inputs:
    command: build 
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '10.0.101'
    installationPath: '$(Agent.ToolsDirectory)/dotnet'