trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: UseDotNet@2
  displayName: 'Install .NET 10 SDK'
  inputs:
    packageType: 'sdk'
    version: '10.0.101'

- script: dotnet restore SportSynchro.sln
  displayName: 'NuGet restore'

- script: dotnet build SportSynchro.sln --configuration Release --no-restore
  displayName: 'Build solution'
