# SportSynchro CI/CD Pipeline
pool:
  vmImage: ubuntu-latest 

steps:
# Install .Net SDK
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '10.0.101'
    installationPath: '$(Agent.ToolsDirectory)/dotnet'

# Build
- task: DotNetCoreCLI@2
  displayName: Build Projects
  inputs:
    command: build 
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

# Test
- task: DotNetCoreCLI@2 
  displayName: Test Projects
  inputs:
    command: test
    projects: '**/*Tests/*.csproj' 
    arguments: '--configuration $(buildConfiguration)'