using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using SportSynchro.Application.Interfaces.Blob;
using SportSynchro.Application.Interfaces.Lookups;
using SportSynchro.Application.Interfaces.Services;
using SportSynchro.Application.Models.Matches;

namespace SportSynchro.Application.Services.Blob;

public sealed class SchedulePdfService : ISchedulePdfService
{
    private readonly ISchedulePdfRepository _pdfRepository;
    private readonly ISeasonResolver _seasonResolver;
    private readonly IMatchService _matchService;

    public SchedulePdfService(
        ISchedulePdfRepository pdfRepository,
        ISeasonResolver seasonResolver,
        IMatchService matchService)
    {
        _pdfRepository = pdfRepository;
        _seasonResolver = seasonResolver;
        _matchService = matchService;
    }

    public async Task<byte[]> GetSchedulePdfAsync(
        int leagueId,
        CancellationToken cancellationToken)
    {
        int seasonId =
            await _seasonResolver.GetCurrentSeasonIdAsync(
                leagueId,
                cancellationToken);

        // 1. Probeer uit Blob
        try
        {
            return await _pdfRepository.ReadAsync(
                leagueId,
                seasonId);
        }
        catch
        {
            // Bestaat niet → genereren
        }

        // 2. Haal schedule op
        IReadOnlyList<MatchModel> matches =
            await _matchService.GetScheduledMatchesByLeagueIdAsync(
                leagueId,
                cancellationToken);

        if (matches.Count == 0)
            return Array.Empty<byte>();

        // 3. Render PDF met QuestPDF
        byte[] pdf = GeneratePdf(matches);

        // 4. Cache in Blob
        await _pdfRepository.WriteAsync(
            pdf,
            leagueId,
            seasonId);

        return pdf;
    }

    private static byte[] GeneratePdf(
        IReadOnlyList<MatchModel> matches)
    {
        QuestPDF.Settings.License = LicenseType.Community;

        List<MatchModel> ordered =
            [.. matches.OrderBy(m => m.MatchDate)];

        string leagueName = ordered[0].LeagueName;

        Document document = Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(40);
                page.DefaultTextStyle(x => x.FontSize(11));

                page.Header()
                    .Text(leagueName)
                    .FontSize(20)
                    .SemiBold()
                    .AlignCenter();

                page.Content().PaddingTop(20).Column(column =>
                {
                    foreach (IGrouping<DateTime, MatchModel> dayGroup in ordered
                        .GroupBy(m => m.MatchDate.Date))
                    {
                        column.Item().PaddingBottom(10).Column(day =>
                        {
                            day.Item()
                                .Text(dayGroup.Key.ToString("dddd dd MMMM yyyy"))
                                .FontSize(14)
                                .Bold();

                            day.Item().LineHorizontal(1);

                            day.Item().Table(table =>
                            {
                                table.ColumnsDefinition(columns =>
                                {
                                    columns.ConstantColumn(60); // time
                                    columns.RelativeColumn();   // home
                                    columns.ConstantColumn(20); // vs
                                    columns.RelativeColumn();   // away
                                });

                                foreach (MatchModel match in dayGroup)
                                {
                                    table.Cell().Text(match.MatchDate.ToString("HH:mm"));
                                    table.Cell().Text(match.HomeTeam);
                                    table.Cell().Text("vs").AlignCenter();
                                    table.Cell().Text(match.AwayTeam);
                                }
                            });
                        });
                    }
                });

                page.Footer()
                    .AlignCenter()
                    .Text(text =>
                    {
                        text.Span("Generated by SportSynchro");
                    });
            });
        });

        return document.GeneratePdf();
    }
}
