<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Sports.Persistence.Abstractions\Sports.Persistence.Abstractions.csproj" />
    <ProjectReference Include="..\Sports.Domain\Sports.Domain.csproj" />
    <ProjectReference Include="..\..\Shared\Shared\Shared.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
